import React from 'react';
import { motion } from 'framer-motion';
import { ScrollText, AlertTriangle, ArrowRight, Mail } from 'lucide-react';

interface TermsPageProps {
  lastUpdated?: string;
}

const sections = [
  {
    id: 'acceptance',
    title: '1. Acceptance of Terms',
    content: `By accessing or using AutoFounder ("Service"), you agree to be bound by these Terms of Service ("Terms"). If you disagree with any part of these terms, you may not access the Service.

These Terms apply to all visitors, users, and others who access or use the Service. By using the Service, you represent that you are at least 16 years of age and have the legal capacity to enter into these Terms.`
  },
  {
    id: 'description',
    title: '2. Description of Service',
    content: `AutoFounder is an AI-powered platform that generates startup blueprints and business plans based on user inputs. The Service includes:

• AI-generated market analysis and strategy
• Product design recommendations
• Technical architecture suggestions
• Financial projections and models
• Pitch deck generation
• Execution roadmaps

The Service is provided "as is" and is intended for informational and planning purposes only. AutoFounder does not guarantee business success or the accuracy of AI-generated content.`
  },
  {
    id: 'accounts',
    title: '3. User Accounts',
    content: `To access certain features, you must register for an account. You agree to:

• Provide accurate, current, and complete information
• Maintain and promptly update your account information
• Keep your password confidential and secure
• Accept responsibility for all activities under your account
• Notify us immediately of any unauthorized access

We reserve the right to suspend or terminate accounts that violate these Terms or for any other reason at our sole discretion.`
  },
  {
    id: 'usage',
    title: '4. Acceptable Use',
    content: `You agree NOT to use the Service to:

• Violate any applicable laws or regulations
• Generate content that is illegal, harmful, or infringes on others' rights
• Attempt to gain unauthorized access to our systems
• Interfere with or disrupt the Service or servers
• Transmit viruses, malware, or other malicious code
• Scrape, crawl, or use automated means to access the Service without permission
• Resell or redistribute the Service without authorization
• Use the Service for competitive analysis of AutoFounder

We may monitor usage and enforce these restrictions.`
  },
  {
    id: 'ip-user',
    title: '5. Your Intellectual Property',
    content: `You retain ownership of all content you input into the Service ("User Content"), including:

• Startup ideas and descriptions
• Business information
• Uploaded documents and data

By using the Service, you grant AutoFounder a limited, non-exclusive license to process your User Content solely for the purpose of providing the Service to you. We do NOT claim ownership of your ideas or use them for any other purpose.`
  },
  {
    id: 'ip-autofounder',
    title: '6. AutoFounder Intellectual Property',
    content: `The Service and its original content (excluding User Content), features, and functionality are owned by AutoFounder and are protected by copyright, trademark, and other intellectual property laws.

This includes:
• The AutoFounder name, logo, and branding
• User interface and design
• AI models and algorithms
• Documentation and marketing materials

You may not copy, modify, distribute, sell, or lease any part of the Service without our written consent.`
  },
  {
    id: 'generated',
    title: '7. AI-Generated Content',
    content: `Content generated by our AI ("Generated Content") is provided for your use. You may:

• Use Generated Content for your business planning
• Modify and adapt Generated Content as needed
• Share Generated Content with investors, partners, and team members

However, you acknowledge that:
• Generated Content may not be unique and similar content may be generated for others
• AI outputs may contain errors or inaccuracies
• Generated Content should be reviewed and validated before relying on it
• AutoFounder makes no guarantees about the quality or suitability of Generated Content`
  },
  {
    id: 'payment',
    title: '8. Payment Terms',
    content: `For paid plans:

• Fees are charged in advance on a monthly or annual basis
• All fees are non-refundable except as required by law
• Prices may change with 30 days' notice
• You authorize us to charge your payment method automatically
• Failed payments may result in service suspension

Free tier users may have usage limits that reset monthly. Exceeding limits may require upgrading to a paid plan.`
  },
  {
    id: 'termination',
    title: '9. Termination',
    content: `You may terminate your account at any time through account settings or by contacting us.

We may terminate or suspend your access immediately, without notice, for any reason, including:
• Violation of these Terms
• Non-payment of fees
• Suspected fraudulent activity
• At our sole discretion

Upon termination:
• Your right to use the Service ceases immediately
• We may delete your account data (subject to our Privacy Policy)
• Provisions that should survive termination will remain in effect`
  },
  {
    id: 'disclaimers',
    title: '10. Disclaimers',
    content: `THE SERVICE IS PROVIDED "AS IS" AND "AS AVAILABLE" WITHOUT WARRANTIES OF ANY KIND, EXPRESS OR IMPLIED.

We specifically disclaim:
• Any warranty of merchantability or fitness for a particular purpose
• Any warranty that the Service will be uninterrupted, timely, secure, or error-free
• Any warranty regarding the accuracy of AI-generated content
• Any warranty that the Service will meet your specific requirements

AI-generated business advice is not a substitute for professional legal, financial, or business counsel.`
  },
  {
    id: 'liability',
    title: '11. Limitation of Liability',
    content: `TO THE MAXIMUM EXTENT PERMITTED BY LAW, AUTOFOUNDER SHALL NOT BE LIABLE FOR:

• Any indirect, incidental, special, consequential, or punitive damages
• Any loss of profits, revenue, data, or business opportunities
• Any damages arising from your use or inability to use the Service
• Any damages resulting from AI-generated content

Our total liability for any claims shall not exceed the amount you paid us in the twelve (12) months preceding the claim.`
  },
  {
    id: 'indemnification',
    title: '12. Indemnification',
    content: `You agree to indemnify and hold harmless AutoFounder, its officers, directors, employees, and agents from any claims, damages, losses, or expenses (including legal fees) arising from:

• Your use of the Service
• Your violation of these Terms
• Your violation of any third-party rights
• Your User Content

This indemnification obligation will survive termination of these Terms.`
  },
  {
    id: 'disputes',
    title: '13. Dispute Resolution',
    content: `Any disputes arising from these Terms or the Service shall be resolved as follows:

1. Informal Resolution: Contact us first to attempt to resolve the dispute informally
2. Arbitration: If informal resolution fails, disputes will be settled by binding arbitration
3. Jurisdiction: Arbitration will take place in San Francisco, California
4. Class Action Waiver: You agree to resolve disputes individually, not as part of a class action

Small claims court actions and injunctive relief for IP violations are excluded from arbitration requirements.`
  },
  {
    id: 'changes',
    title: '14. Changes to Terms',
    content: `We reserve the right to modify these Terms at any time. Material changes will be communicated:

• By posting updated Terms with a new "Last Updated" date
• By email notification to registered users
• By prominent notice in the Service

Your continued use of the Service after changes constitutes acceptance. If you disagree with changes, you must stop using the Service.`
  },
  {
    id: 'general',
    title: '15. General Provisions',
    content: `• Entire Agreement: These Terms constitute the entire agreement between you and AutoFounder
• Severability: If any provision is found unenforceable, others remain in effect
• Waiver: Failure to enforce any right does not waive that right
• Assignment: You may not assign these Terms; we may assign them freely
• Governing Law: These Terms are governed by California law
• Contact: Questions about these Terms should be sent to legal@autofounder.io`
  }
];

const TermsPage: React.FC<TermsPageProps> = ({ lastUpdated = 'December 15, 2025' }) => {
  return (
    <div className="min-h-screen bg-white dark:bg-gray-950">
      {/* Hero */}
      <section className="relative pt-32 pb-16 px-6">
        <div className="max-w-4xl mx-auto">
          <motion.div
            initial={{ opacity: 0, y: 10 }}
            animate={{ opacity: 1, y: 0 }}
            className="inline-flex items-center gap-2 px-3 py-1 rounded-full bg-brand-50 dark:bg-brand-900/30 text-brand-600 dark:text-brand-400 text-xs font-semibold mb-6"
          >
            <ScrollText className="w-3 h-3" />
            Legal
          </motion.div>

          <motion.h1
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ delay: 0.1 }}
            className="text-4xl md:text-5xl font-bold text-gray-900 dark:text-white mb-4 tracking-tight"
          >
            Terms of Service
          </motion.h1>

          <motion.p
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ delay: 0.2 }}
            className="text-xl text-gray-600 dark:text-gray-400 mb-4"
          >
            Please read these terms carefully before using AutoFounder.
          </motion.p>

          <motion.p
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ delay: 0.3 }}
            className="text-sm text-gray-500"
          >
            Last updated: {lastUpdated}
          </motion.p>
        </div>
      </section>

      {/* Important Notice */}
      <section className="py-6 px-6">
        <div className="max-w-4xl mx-auto">
          <motion.div
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ delay: 0.4 }}
            className="flex items-start gap-4 p-6 rounded-2xl bg-amber-50 dark:bg-amber-900/20 border border-amber-200 dark:border-amber-800"
          >
            <AlertTriangle className="w-6 h-6 text-amber-600 dark:text-amber-400 flex-shrink-0 mt-0.5" />
            <div>
              <h3 className="font-bold text-amber-900 dark:text-amber-200 mb-1">
                Important Notice
              </h3>
              <p className="text-amber-800 dark:text-amber-300 text-sm">
                By using AutoFounder, you agree to these Terms. Section 11 limits our liability and Section 13 requires arbitration for disputes.
              </p>
            </div>
          </motion.div>
        </div>
      </section>

      {/* Table of Contents */}
      <section className="py-8 px-6 border-b border-gray-100 dark:border-gray-800">
        <div className="max-w-4xl mx-auto">
          <h2 className="text-sm font-bold text-gray-500 uppercase tracking-wider mb-4">
            Table of Contents
          </h2>
          <div className="grid md:grid-cols-3 gap-2">
            {sections.map((section) => (
              <a
                key={section.id}
                href={`#${section.id}`}
                className="px-3 py-2 rounded-lg hover:bg-gray-100 dark:hover:bg-gray-800 text-gray-600 dark:text-gray-400 text-sm transition-colors"
              >
                {section.title}
              </a>
            ))}
          </div>
        </div>
      </section>

      {/* Content */}
      <section className="py-16 px-6">
        <div className="max-w-4xl mx-auto space-y-16">
          {sections.map((section) => (
            <motion.div
              key={section.id}
              id={section.id}
              initial={{ opacity: 0, y: 20 }}
              whileInView={{ opacity: 1, y: 0 }}
              viewport={{ once: true, margin: "-100px" }}
            >
              <h2 className="text-2xl font-bold text-gray-900 dark:text-white mb-4">
                {section.title}
              </h2>
              <div className="prose prose-gray dark:prose-invert max-w-none">
                <p className="text-gray-600 dark:text-gray-400 whitespace-pre-line leading-relaxed">
                  {section.content}
                </p>
              </div>
            </motion.div>
          ))}
        </div>
      </section>

      {/* Contact */}
      <section className="py-20 px-6 bg-gray-50 dark:bg-gray-900/50">
        <div className="max-w-2xl mx-auto text-center">
          <Mail className="w-12 h-12 text-brand-500 mx-auto mb-6" />
          <h3 className="text-2xl font-bold text-gray-900 dark:text-white mb-4">
            Questions about our terms?
          </h3>
          <p className="text-gray-600 dark:text-gray-400 mb-8">
            Contact our legal team at legal@autofounder.io
          </p>
          <a
            href="mailto:legal@autofounder.io"
            className="inline-flex items-center gap-2 px-8 py-4 rounded-full bg-gray-900 dark:bg-white text-white dark:text-gray-900 font-semibold hover:opacity-90 transition-all"
          >
            Contact Legal Team
            <ArrowRight className="w-5 h-5" />
          </a>
        </div>
      </section>
    </div>
  );
};

export default TermsPage;
