import React, { useRef } from 'react';
import { motion, useScroll, useTransform } from 'framer-motion';
import { Target, Code, TrendingUp, CheckCircle2, Rocket, Sparkles, LucideIcon, ArrowRight } from 'lucide-react';

interface Capability {
  icon: LucideIcon;
  title: string;
  description: string;
  color: string;
}

const capabilities: Capability[] = [
  {
    icon: Target,
    title: "Strategy & Market",
    description: "Positioning, moat, TAM, and competitive map grounded in first-principles reasoning.",
    color: "brand"
  },
  {
    icon: Code,
    title: "Technical Scaffolding",
    description: "Architecture, API design, data model, and repo structure—ready for handoff to engineers.",
    color: "blue"
  },
  {
    icon: TrendingUp,
    title: "Viability Scoring",
    description: "Multi-dimensional scoring across feasibility, timing, revenue potential, risk, and resourcing.",
    color: "green"
  },
  {
    icon: CheckCircle2,
    title: "Product Definition",
    description: "User journeys, feature sequencing, acceptance criteria, and crisp release notes.",
    color: "purple"
  },
  {
    icon: Rocket,
    title: "Execution Roadmap",
    description: "Week-by-week sprints with owners, milestones, and success metrics.",
    color: "orange"
  },
  {
    icon: Sparkles,
    title: "Pitch & Narrative",
    description: "Investor and founder voice scripts plus a one-slide story spine.",
    color: "pink"
  }
];

const colorClassMap: Record<string, { bg: string; text: string; border: string; glow: string }> = {
  brand: { bg: 'bg-blue-50 dark:bg-blue-950/30', text: 'text-blue-600 dark:text-blue-400', border: 'border-blue-200 dark:border-blue-800', glow: 'group-hover:shadow-lg group-hover:shadow-blue-500/10' },
  blue: { bg: 'bg-cyan-50 dark:bg-cyan-950/30', text: 'text-cyan-600 dark:text-cyan-400', border: 'border-cyan-200 dark:border-cyan-800', glow: 'group-hover:shadow-lg group-hover:shadow-cyan-500/10' },
  green: { bg: 'bg-emerald-50 dark:bg-emerald-950/30', text: 'text-emerald-600 dark:text-emerald-400', border: 'border-emerald-200 dark:border-emerald-800', glow: 'group-hover:shadow-lg group-hover:shadow-emerald-500/10' },
  purple: { bg: 'bg-purple-50 dark:bg-purple-950/30', text: 'text-purple-600 dark:text-purple-400', border: 'border-purple-200 dark:border-purple-800', glow: 'group-hover:shadow-lg group-hover:shadow-purple-500/10' },
  orange: { bg: 'bg-orange-50 dark:bg-orange-950/30', text: 'text-orange-600 dark:text-orange-400', border: 'border-orange-200 dark:border-orange-800', glow: 'group-hover:shadow-lg group-hover:shadow-orange-500/10' },
  pink: { bg: 'bg-pink-50 dark:bg-pink-950/30', text: 'text-pink-600 dark:text-pink-400', border: 'border-pink-200 dark:border-pink-800', glow: 'group-hover:shadow-lg group-hover:shadow-pink-500/10' }
};

/**
 * Capabilities Section - Apple Level Design
 * 
 * Clean, minimal showcase with:
 * - Simple, elegant cards
 * - Monochromatic icon treatment
 * - Subtle hover states
 * - Maximum clarity and readability
 */
const Capabilities: React.FC = () => {
  const ref = useRef<HTMLElement>(null);
  const { scrollYProgress } = useScroll({
    target: ref,
    offset: ["start end", "end start"]
  });

  const opacity = useTransform(scrollYProgress, [0, 0.3, 0.7, 1], [0, 1, 1, 0]);

  return (
    <section ref={ref} className="relative py-32 px-6 md:px-8 bg-gradient-to-b from-slate-100 via-white to-slate-50 dark:from-slate-900 dark:via-slate-950 dark:to-slate-900 overflow-hidden">
      <div className="pointer-events-none absolute inset-0 opacity-40 [background:radial-gradient(ellipse_at_25%_35%,rgba(59,130,246,0.10),transparent_35%),radial-gradient(ellipse_at_75%_65%,rgba(168,85,247,0.08),transparent_40%)]" />
      <motion.div className="relative max-w-6xl mx-auto" style={{ opacity }}>
        {/* Section Header */}
        <motion.div 
          className="mb-20 max-w-3xl"
          initial={{ opacity: 0, y: 20 }}
          whileInView={{ opacity: 1, y: 0 }}
          viewport={{ once: true, margin: "-100px" }}
          transition={{ duration: 0.6 }}
        >
          <h2 className="text-5xl md:text-6xl font-black tracking-tight mb-6 text-slate-900 dark:text-white leading-[1.1]">
            Everything included
          </h2>
          
          <p className="text-base md:text-lg text-slate-600 dark:text-slate-400 leading-relaxed font-normal">
            Every piece of your startup blueprint, generated by AI and grounded in proven patterns from successful companies.
          </p>
        </motion.div>

        {/* Capability Cards Grid */}
        <motion.div className="grid md:grid-cols-2 lg:grid-cols-3 gap-6">
          {capabilities.map((capability, index) => {
            const Icon = capability.icon;
            const colorClasses = colorClassMap[capability.color];

            return (
              <motion.div
                key={index}
                initial={{ opacity: 0, y: 20 }}
                whileInView={{ opacity: 1, y: 0 }}
                viewport={{ once: true, margin: "-50px" }}
                transition={{ duration: 0.5, delay: index * 0.1 }}
                whileHover={{ y: -8 }}
                className="group"
              >
                <div className={`relative p-7 rounded-2xl border ${colorClasses.border} bg-white dark:bg-slate-800/80 backdrop-blur-xl transition-all duration-500 ${colorClasses.glow} hover:border-opacity-100 shadow-[0_20px_100px_rgba(15,23,42,0.12)]`}>
                  {/* Icon Container */}
                  <motion.div 
                    className={`w-14 h-14 rounded-xl ${colorClasses.bg} flex items-center justify-center mb-5 ${colorClasses.text}`}
                    whileHover={{ scale: 1.12, rotate: -5 }}
                    transition={{ type: "spring", stiffness: 400, damping: 20 }}
                  >
                    <Icon className="w-7 h-7" />
                  </motion.div>

                  {/* Content */}
                  <h3 className="text-lg font-bold mb-2 text-slate-900 dark:text-white group-hover:text-opacity-90 transition-colors">
                    {capability.title}
                  </h3>
                  
                  <p className="text-slate-600 dark:text-slate-400 leading-relaxed text-sm font-normal">
                    {capability.description}
                  </p>
                  
                  {/* Hover indicator */}
                  <motion.div
                    className="absolute bottom-4 right-4 opacity-0 group-hover:opacity-100 transition-opacity"
                    initial={{ x: -10 }}
                    whileHover={{ x: 0 }}
                  >
                    <ArrowRight className={`w-5 h-5 ${colorClasses.text}`} />
                  </motion.div>
                </div>
              </motion.div>
            );
          })}
        </motion.div>
      </motion.div>
    </section>
  );
};

export default Capabilities;
