import React, { useRef } from 'react';
import { motion, useScroll, useTransform } from 'framer-motion';
import { Target, Code, TrendingUp, CheckCircle2, Rocket, Sparkles, FileText, PieChart, Lightbulb, Layers } from 'lucide-react';

/**
 * Capabilities Section - Apple-Level Bento Grid Design
 * 
 * Features:
 * - Beautiful bento grid layout
 * - Glassmorphism cards
 * - Smooth scroll animations
 * - Interactive hover states
 * - Dynamic content arrangement
 */

interface CapabilityCard {
  icon: React.ElementType;
  title: string;
  description: string;
  gradient: string;
  iconBg: string;
  size?: 'default' | 'large' | 'wide';
}

const capabilities: CapabilityCard[] = [
  {
    icon: Target,
    title: "Market Strategy",
    description: "TAM analysis, competitive positioning, and go-to-market strategy grounded in real market data.",
    gradient: "from-blue-500/10 to-cyan-500/10",
    iconBg: "from-blue-500 to-cyan-500",
    size: 'large'
  },
  {
    icon: Layers,
    title: "Product Design",
    description: "User journeys, feature specs, and wireframe concepts.",
    gradient: "from-purple-500/10 to-pink-500/10",
    iconBg: "from-purple-500 to-pink-500",
  },
  {
    icon: Code,
    title: "Tech Architecture",
    description: "Stack recommendations, API design, and database schema.",
    gradient: "from-emerald-500/10 to-teal-500/10",
    iconBg: "from-emerald-500 to-teal-500",
  },
  {
    icon: TrendingUp,
    title: "Viability Scoring",
    description: "10-dimensional analysis covering feasibility, timing, competition, and market fit with actionable insights.",
    gradient: "from-amber-500/10 to-orange-500/10",
    iconBg: "from-amber-500 to-orange-500",
    size: 'wide'
  },
  {
    icon: Rocket,
    title: "Execution Roadmap",
    description: "Sprint-by-sprint plan with milestones and KPIs.",
    gradient: "from-rose-500/10 to-red-500/10",
    iconBg: "from-rose-500 to-red-500",
  },
  {
    icon: FileText,
    title: "Pitch Scripts",
    description: "VC-ready and founder voice pitches that resonate.",
    gradient: "from-indigo-500/10 to-violet-500/10",
    iconBg: "from-indigo-500 to-violet-500",
  },
  {
    icon: PieChart,
    title: "Financial Model",
    description: "Revenue projections, unit economics, and pricing strategy tailored to your business model.",
    gradient: "from-cyan-500/10 to-blue-500/10",
    iconBg: "from-cyan-500 to-blue-500",
    size: 'large'
  },
];

const Capabilities: React.FC = () => {
  const sectionRef = useRef<HTMLElement>(null);
  const { scrollYProgress } = useScroll({
    target: sectionRef,
    offset: ["start end", "end start"]
  });

  const opacity = useTransform(scrollYProgress, [0, 0.2, 0.8, 1], [0, 1, 1, 0]);
  const y = useTransform(scrollYProgress, [0, 0.2], [50, 0]);

  return (
    <section 
      ref={sectionRef} 
      id="features"
      className="relative py-32 px-6 lg:px-8 overflow-hidden"
    >
      {/* Background */}
      <div className="absolute inset-0 bg-gradient-to-b from-gray-100/50 via-white to-white dark:from-gray-900/50 dark:via-gray-950 dark:to-gray-950" />

      <motion.div 
        className="relative max-w-6xl mx-auto"
        style={{ opacity }}
      >
        {/* Section Header */}
        <motion.div 
          className="text-center mb-20"
          initial={{ opacity: 0, y: 30 }}
          whileInView={{ opacity: 1, y: 0 }}
          viewport={{ once: true, margin: "-100px" }}
          transition={{ duration: 0.6 }}
        >
          <motion.div 
            className="inline-flex items-center gap-2 px-4 py-2 rounded-full bg-brand-50 dark:bg-brand-950/30 border border-brand-200/50 dark:border-brand-800/30 mb-6"
            initial={{ opacity: 0, scale: 0.9 }}
            whileInView={{ opacity: 1, scale: 1 }}
            viewport={{ once: true }}
            transition={{ delay: 0.1 }}
          >
            <Sparkles className="w-4 h-4 text-brand-600 dark:text-brand-400" />
            <span className="text-sm font-medium text-brand-700 dark:text-brand-300">Complete toolkit</span>
          </motion.div>

          <h2 className="text-4xl sm:text-5xl lg:text-6xl font-bold tracking-tight text-gray-900 dark:text-white mb-6">
            Everything you need to{' '}
            <span className="gradient-text">launch</span>
          </h2>
          
          <p className="max-w-2xl mx-auto text-lg text-gray-600 dark:text-gray-400 leading-relaxed">
            Every component of your startup blueprint, generated by AI and refined by patterns from thousands of successful companies.
          </p>
        </motion.div>

        {/* Bento Grid */}
        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-5">
          {capabilities.map((capability, index) => {
            const Icon = capability.icon;
            const isLarge = capability.size === 'large';
            const isWide = capability.size === 'wide';
            
            return (
              <motion.div
                key={capability.title}
                className={`group relative rounded-3xl overflow-hidden ${
                  isLarge ? 'md:row-span-2' : ''
                } ${isWide ? 'md:col-span-2' : ''}`}
                initial={{ opacity: 0, y: 30 }}
                whileInView={{ opacity: 1, y: 0 }}
                viewport={{ once: true, margin: "-50px" }}
                transition={{ duration: 0.5, delay: index * 0.08 }}
              >
                <div className={`
                  relative h-full p-8 
                  bg-white/60 dark:bg-gray-900/40 
                  backdrop-blur-xl 
                  border border-black/[0.04] dark:border-white/[0.06]
                  transition-all duration-500 ease-out
                  group-hover:bg-white/80 dark:group-hover:bg-gray-900/60
                  group-hover:border-black/[0.08] dark:group-hover:border-white/[0.1]
                  group-hover:shadow-apple-lg
                  group-hover:-translate-y-1
                `}>
                  {/* Gradient overlay on hover */}
                  <div className={`absolute inset-0 bg-gradient-to-br ${capability.gradient} opacity-0 group-hover:opacity-100 transition-opacity duration-500`} />
                  
                  {/* Content */}
                  <div className="relative z-10 h-full flex flex-col">
                    {/* Icon */}
                    <motion.div 
                      className={`w-14 h-14 rounded-2xl bg-gradient-to-br ${capability.iconBg} flex items-center justify-center shadow-lg mb-6`}
                      whileHover={{ scale: 1.1, rotate: -5 }}
                      transition={{ type: "spring", stiffness: 400, damping: 15 }}
                    >
                      <Icon className="w-7 h-7 text-white" />
                    </motion.div>

                    {/* Title */}
                    <h3 className="text-xl font-semibold text-gray-900 dark:text-white mb-3">
                      {capability.title}
                    </h3>
                    
                    {/* Description */}
                    <p className={`text-gray-600 dark:text-gray-400 leading-relaxed ${isLarge ? 'text-base' : 'text-sm'}`}>
                      {capability.description}
                    </p>

                    {/* Spacer for consistent layout */}
                    <div className="flex-1" />

                    {/* Hover indicator */}
                    <motion.div
                      className="mt-6 flex items-center gap-2 text-sm font-medium text-gray-500 dark:text-gray-400 opacity-0 group-hover:opacity-100 transition-opacity"
                      initial={{ x: -10 }}
                      whileHover={{ x: 0 }}
                    >
                      <span>Learn more</span>
                      <motion.span
                        animate={{ x: [0, 4, 0] }}
                        transition={{ duration: 1.5, repeat: Infinity }}
                      >
                        →
                      </motion.span>
                    </motion.div>
                  </div>
                </div>
              </motion.div>
            );
          })}
        </div>

        {/* Bottom CTA */}
        <motion.div 
          className="mt-16 text-center"
          initial={{ opacity: 0, y: 20 }}
          whileInView={{ opacity: 1, y: 0 }}
          viewport={{ once: true }}
          transition={{ delay: 0.5 }}
        >
          <p className="text-gray-500 dark:text-gray-400 text-sm">
            All modules generated in a single pass • Exported as structured JSON & PDF
          </p>
        </motion.div>
      </motion.div>
    </section>
  );
};

export default Capabilities;
